djangoapp/artist/urls.py
from django.conf.urls import url

from . import views

app_name = 'artist'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^gallery/', views.gallery, name='gallery'),
	url(r'^about/', views.about, name='about'),
	url(r'^contact/', views.contact, name='contact'),
]

djangoapp/djangoapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^artist/', include('artist.urls')),
    url(r'^admin/', admin.site.urls),
]

djangoapp/artist/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

djangoapp/artist/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'artist/index.html')

def gallery(request):
	return render(request, 'artist/gallery.html')

def about(request):
	return render(request, 'artist/about.html')

def contact(request):
	return render(request, 'artist/contact.html')

djangoapp/artist/templates/artist/about.html
{% extends 'artist/base.html' %}

{% block css %} 
	<link rel="stylesheet" type="text/css" href="/static/artist/about.css" /> 
{% endblock %}

{% block title %} About {% endblock %}

{% block page-title %} 
	<h3> Placeholder title for about </h3> 
{% endblock %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'artist:index' %}"> Home</a></li>
    <li><a href="{% url 'artist:gallery' %}"> Gallery</a></li>
    <li class="active"><a href="{% url 'artist:about' %}"> About</a></li>
    <li><a href="{% url 'artist:contact' %}"> Contact</a></li>
</ul>
{% endblock %}
{% block content %}
	<p> Sample content </p>
{% endblock %}

djangoapp/artist/templates/artist/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap Pulldown -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'artist/base.css' %}" />
    {% block css %} {% endblock %}

    <title>{% block title %} Artist WebApp {% endblock %}</title>
</head>

<body>
    <div class="container" id="page-title">
        {% block page-title %}
        <h3> Page Title </h3>
        {% endblock %}
    </div>

    <div class="container" id="navbar">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span> 
                    </button>
                    <a class="navbar-brand" href="{%url 'artist:index' %}">WebSiteName</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    {% block navbar %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'artist:index' %}"> Home</a></li>
                        <li><a href="{% url 'artist:gallery' %}"> Gallery</a></li>
                        <li><a href="{% url 'artist:about' %}"> About</a></li>
                        <li><a href="{% url 'artist:contact' %}"> Contact</a></li>
                    </ul>
                    {% endblock %}
                </div>
            </div>
        </nav>
    </div>

    <div class="container" id="content">
        {% block content %} {% endblock %}
    </div>

</body>
</html>

djangoapp/artist/templates/artist/contact.html
{% extends 'artist/base.html' %}

{% block css %} 
	<link rel="stylesheet" type="text/css" href="/static/artist/contact.css" /> 
{% endblock %}

{% block title %} Contact {% endblock %}

{% block page-title %} 
	<h3> Placeholder title for contact </h3> 
{% endblock %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'artist:index' %}"> Home</a></li>
    <li><a href="{% url 'artist:gallery' %}"> Gallery</a></li>
    <li><a href="{% url 'artist:about' %}"> About</a></li>
    <li class="active"><a href="{% url 'artist:contact' %}"> Contact</a></li>
</ul>
{% endblock %}

{% block content %}
	<p> Sample content </p>
{% endblock %}

djangoapp/artist/templates/artist/gallery.html
{% extends 'artist/base.html' %}

{% block css %} 
	<link rel="stylesheet" type="text/css" href="/static/artist/gallery.css" /> 
{% endblock %}

{% block title %} Gallery {% endblock %}

{% block page-title %} 
	<h3> Placeholder title for gallery </h3> 
{% endblock %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'artist:index' %}"> Home</a></li>
    <li class="active"><a href="{% url 'artist:gallery' %}"> Gallery</a></li>
    <li><a href="{% url 'artist:about' %}"> About</a></li>
    <li><a href="{% url 'artist:contact' %}"> Contact</a></li>
</ul>
{% endblock %}

{% block content %}
<div class="col-lg-12">
	<h1> Gallery </h1>
	<hr>
</div>

<!-- 
Need to pass a dictionary of information about each image into this template, should have: (title, url, caption) -> 
	this image needs to go into the data-... below 

Should do ranged loop over the dictionary instead of this horrible thing below
-->
{% for x in "xxxxxxxxxxxx" %}
	<div class="col-lg-3 col-md-4 col-xs-6 thumb">
		<a class="thumbnail" href="#" data-toggle="modal" data-target="#modal" data-title="Sledge" data-url="http://placehold.it/350x350" data-caption="Sample caption: 12x12 Watercolor">
			<img class="img-responsive" src="http://placehold.it/350x350" alt title style>
		</a>
	</div>

	<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
	                <h4 class="modal-title" id="image-gallery-title"> Placeholder title </h4>
	            </div>
	            <div class="modal-body">
	                <img id="modal-img" class="img-responsive" src="">
	            </div>
	            <div class="modal-footer">
		                <p id="modal-caption"> Placeholder caption </p>
	            </div>
	        </div>
	    </div>
	</div>
{% endfor %}

<!-- Move this to seperate file, this code handles setting the appropriate information in the modal -->
<script> 
	$(document).on("click", ".thumbnail", function() {
		var title = $(this).data('title');
		var url = $(this).data('url');
		var caption = $(this).data('caption');

		$("#image-gallery-title").text(title);
		$("#modal-img").attr('src', url);
		$("#modal-caption").text(caption);
	});
</script>

{% endblock %}

djangoapp/artist/templates/artist/index.html
{% extends 'artist/base.html' %}

{% block css %} 
	<link rel="stylesheet" type="text/css" href="/static/artist/index.css" /> 
{% endblock %}

{% block title %} Home {% endblock %}

{% block page-title %} 
	<h3> Placeholder title for home </h3> 
{% endblock %}

{% block navbar %}
<ul class="nav navbar-nav">
    <li class="active"><a href="{% url 'artist:index' %}"> Home</a></li>
    <li><a href="{% url 'artist:gallery' %}"> Gallery</a></li>
    <li><a href="{% url 'artist:about' %}"> About</a></li>
    <li><a href="{% url 'artist:contact' %}"> Contact</a></li>
</ul>
{% endblock %}

{% block content %}
	<p> Sample content </p>
{% endblock %}